### ISSUE TITLE
Lazysizes choosing the incorrect size randomly

### ISSUE THREAD

**Issue by JayK31** [aFarkas/lazysizes#733] opened 2019-12-28 16:31 UTC
**Describe the bug**
LS seems to be incorrectly sizing certain images for reasons that I cannot understand. Most of the images on my site are fine.

**To Reproduce**
There are images on this page that are all sized differently. Their CSS is the same. The image on the far right (Extra Fancy, Gourmet Artisanal) is the correct size.
https://taprm.com/collections/de-ranke

**What is the expected behavior**
<img width="861" alt="image" src="https://user-images.githubusercontent.com/6744116/71546494-4720f780-2965-11ea-8164-76977092623b.png">

**What happened instead**
<img width="820" alt="image" src="https://user-images.githubusercontent.com/6744116/71546483-31133700-2965-11ea-886b-823ead3f4748.png">

**In what environment (browser/device etc.) does this bug happen/not happen:**
This seems to happen across all browsers and devices

**Comment by aFarkas** [comment] 2019-12-28 21:19
@JayK31 
This is by design. The native `sizes` feature forces you, that you write your layout related stuff into your HTML. This is fixed by lazysizes by taking the current `sizes` information from your CSS and adding it to the DOM. This means lazysizes needs layout information inside of your CSS and this is missing in your case. If you use `width: auto` lazysizes has no information about your image and it might look random to you...

There are two ways to fix it both are described in the readme. Pleas read it!

1. Add `width`
2. Hook into the `lazybeforesizes` event and create your own logic.

**Closed by aFarkas** 2019-12-28 21:19 UTC
