### ISSUE TITLE
bget gets stuck 'lazyloading' using bgset since Firefox Update 38

### ISSUE THREAD

**Issue by jannicz** [aFarkas/lazysizes#106] opened 2015-05-29 13:51 UTC
Hi Alex,

we are using lazysizes with the bgset plugin (and customMedia definitions) for responsive background images. The latest is causing problems. It worked for months in most browsers until the Firefox Update 38! Since then FF38 stucks 'lazyloading' on the div with the background-image (the hidden picture tag is being created correctly though). Maybe some problems in parsing the customMedia string?

Compare the prepared jsfiddle in Chrome and FF38 and you will see the difference: http://jsfiddle.net/acsj9s1e/9/

**Comment by aFarkas** [comment] 2015-05-29 17:56
Could you please confirm, that the newest version in master (https://cdn.rawgit.com/aFarkas/lazysizes/master/lazysizes.js, https://cdn.rawgit.com/aFarkas/lazysizes/master/plugins/bgset/ls.bgset.js, https://cdn.rawgit.com/aFarkas/lazysizes/master/plugins/respimg/ls.respimg.js), now works in your environment?

Here is a working fiddle:
http://jsfiddle.net/trixta/k1ff6fx2/2/

> It worked for months in most browsers

Which browsers did not work? Do they work now?

There is also something, with your markup:

1. With ``picture`` element always the first ``source``, that matches is chosen. This means you can use either only min-* or max-*:

```js
window.lazySizesConfig.customMedia = {
    '--s': '(max-width: 479px)',
    '--m': '(max-width: 991px)',
    '--l': '(max-width: 1536px)'
};
```
2. Your "set" has no source defined for a screen larger than 1536px, is this right? Normally you should do something like this:

```
data-bgset="http://placehold.it/300x150 [--s] |
        http://placehold.it/500x250 [--m] |
        http://placehold.it/1000x500"
```

Or:

```
data-bgset="http://placehold.it/300x150 [--s] |
        http://placehold.it/500x250 [--m] |
        http://placehold.it/1000x500 [--l] | 
        transparant.png"
```

**Comment by aFarkas** [comment] 2015-06-02 08:35
@jannicz 
Any news on this?

**Comment by jannicz** [comment] 2015-06-02 13:24
@aFarkas: the optional set for images larger than 1536px somehow changes the symptoms. But I can confirm the problem remains after applying the suggested changes in Firefox 38;

see http://jsfiddle.net/k1ff6fx2/3/

Other browsers work as expected, the current Firefox stucks 'lazyloading' without the optional image (here: screen larger than 1536px) and always loads the optional picture (and onlym this) when it is provided in the set. In both cases: FF38 never switches the image.

![ff38_large_viewport](https://cloud.githubusercontent.com/assets/9930138/7936601/aeaa19cc-093a-11e5-8c6a-20904cb58819.png)
FF38 in large viewport

![ff38_small_viewport](https://cloud.githubusercontent.com/assets/9930138/7936700/74097b68-093b-11e5-8cc7-594aa8ffe896.png)

FF38 in small viewport (wrong image)

**Comment by aFarkas** [comment] 2015-06-02 17:48
@jannicz 

Ok, thx. Basically you do describe two errors (in fact more).

Here is a new fiddle to check for you (http://jsfiddle.net/trixta/k1ff6fx2/). I think I already fixed this error with "getting stuck in lazyloading mode/state". To clarify this, I have added a red border for lazyloading and a blue border for lazyloaded. For me it switches now always to lazyloaded.

I can confirm, that FF now always loaded the last source. This is a [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1170572). Fortunately, I found a workaround for this. So this should be fixed now.

Beside all of this I also found a [chrome issue](https://code.google.com/p/chromium/issues/detail?id=493817) and worked around...

So could you now re-check with the newest version on master. (I would like to do a quick release with all those fixes.) Keep me busy.

**Comment by jannicz** [comment] 2015-06-03 07:32
I can confirm that now both errors are fixed in master:
* FF always switches to lazyloaded, even if last optional source is missing
* FF correctly selects the right image according to viewport

Also tested Chorme 43 and IE11.

Aperto says thanks you ;-)

**Comment by aFarkas** [comment] 2015-06-03 09:20
yeah. greetings.

**Closed by aFarkas** 2015-06-03 09:20 UTC

**Comment by aFarkas** [comment] 2015-07-27 12:08
@jannicz 
Just because we talked about it. still online

```html
<div class="teaser teaser-cs image-teaser">
    <div class="detail">
        <div class="image">
        <a href="#" target="_blank">
            <img class="product" src="#" alt="Do it + Garden">
        </a>
        </div><!--image-->
    	<h2><a href="#" target="_blank"><br></a></h2>
    	<h3><a href="#" target="_blank"><br></a></h3>
        <div class="info">
        <p><strong>Festbankgarnitur</strong><br> Schweizer Qualitätsprodukt<br> <strong>Fr. 126.-</strong> statt Fr. 169.-</p>
        </div><!-- end info -->
        <div class="links">
            <ul>
                <li class="external">
                    <a href="#" target="_blank" title="Link auf ">Zum Angebot</a>
                </li>
            </ul>
        </div>
    </div><!--detail-->
</div>
```

**Comment by zeppelinen** [comment] 2020-08-25 09:53
@aFarkas  Hi!
I am looking for a working example of bgset, because the fiddle you posted is not working anymore in recent chrome versions.

> @jannicz
> 
> Ok, thx. Basically you do describe two errors (in fact more).
> 
> Here is a new fiddle to check for you (http://jsfiddle.net/trixta/k1ff6fx2/). I think I already fixed this error with "getting stuck in lazyloading mode/state". To clarify this, I have added a red border for lazyloading and a blue border for lazyloaded. For me it switches now always to lazyloaded.
> 
> I can confirm, that FF now always loaded the last source. This is a [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1170572). Fortunately, I found a workaround for this. So this should be fixed now.
> 
> Beside all of this I also found a [chrome issue](https://code.google.com/p/chromium/issues/detail?id=493817) and worked around...
> 
> So could you now re-check with the newest version on master. (I would like to do a quick release with all those fixes.) Keep me busy.
