### ISSUE TITLE
Chrome loads incorrect source when using auto sizes

### ISSUE THREAD

**Issue by JimmyLeonardson** [aFarkas/lazysizes#224] opened 2016-02-08 16:10 UTC
When using auto sizes the source image loaded is inconsistent in Chrome Version 48.0.2564.103. 
Works fine in Firefox and Safari.

1. On page load sometimes the incorrect source (too large) is loaded. This occurs more often on smaller sizes but sometimes the same source is applied to all images.
2. On resizing the window every image is changed to the largest source.

See my codepen: 
http://codepen.io/anon/pen/LGXGJx

Please compare results between Chrome and Firefox/Safari

**Comment by aFarkas** [comment] 2016-02-08 19:07
I think this is a duplicate of this:
https://github.com/aFarkas/lazysizes/issues/133

please close if you think so too or explain why not.

**Comment by JimmyLeonardson** [comment] 2016-02-08 22:35
Yes It might be that Chrome caches and reuses the first image, however even disabling cache in devtools I get strange results which are not consistent like in Firefox or Safari. I'll do some tests with only unique images in various sizes to see  how it behaves and post the results here.

**Comment by JimmyLeonardson** [comment] 2016-02-09 09:13
I updated the pen with unique sources and now it seems to work. When I open it in a incognito window in small viewport it loads the smaller versions. You could easily be tricked by the algorithms of Chrome. :) Closing.

**Closed** 2016-02-09 09:13 UTC
