### ISSUE TITLE
Can't get bgset to work

### ISSUE THREAD

**Issue by TPDBrendan** [aFarkas/lazysizes#47] opened 2015-01-29 15:48 UTC
This has been a really useful script for lazyloading individual background images via unveilhooks, but I can't seem to get the bgset plugin to work at all.  In Chrome it seems to load at least one image, but doesn't switch out when the viewport changes.  It doesn't request the images at all in Firefox or Safari.  

I've tried it locally with picturefill, rias, and respimage, but none of them seem to do the trick.

Am I missing something really simple?

Link here:
http://codepen.io/TPDBrendan/pen/azyYKx

**Comment by aFarkas** [comment] 2015-01-29 19:37
I'm very sorry. Will look into this soon.

**Comment by aFarkas** [comment] 2015-01-30 13:11
The plugin was actually working, but had some problems, because the polyfill (respimage or picturefill) can be loaded to late. The fact, that Chrome doesn't change the size, was due to the fact that I was to lazy to also implement this.

I just changed and improved those things and here is a working example of this plugin:
http://jsfiddle.net/trixta/bfqqnosp/embedded/result/

Please let me know whether this helps.

**Comment by TPDBrendan** [comment] 2015-01-30 14:54
Hey, thanks for taking the time to work on this.  I'm not sure if I'm missing something, but it looks like it works upon load in Firefox, but not on resizing the viewport, and that it doesn't work at all in Chrome.  I don't know if I'm not looking at it correctly, though.  

Before finding your plugin, I was setting the sources of different image sizes as data-attributes and then using enquireJS to inline them.  This works just like a CSS media query across all browsers, so I'm going to stick with that.

I was just hoping I could use bgSet because I really like how unveilhooks had worked for non-responsive BG images so far and I was hoping to use one less script and get the lazyload effect with media queries.  I appreciate the help, though!

**Comment by aFarkas** [comment] 2015-01-30 15:30
@TPDBrendan 
Thx, for feedback. I think you are looking at this in a wrong way. But please help me to confirm, that it is not a bug.

The ``data-bgset`` feature is basically based on the native ``srcset`` feature. The ``srcset`` feature means, that all images in the list are the same image, but only have different image sizes. If the browser has an image that is large enough it will not switch the source.

You can test this by doing the following steps:

1. open http://jsfiddle.net/trixta/bfqqnosp/embedded/result/
2. resize your window to make it less than 800px wide
3. clear your cache
4. reload
5. resize your window to make it wider than 1200px

You should see that it image will be switched than. Can you confirm this.

What you seem to need is something like a mediaset feature, which is working with media queries:

Something like this:

```html
<div class="lazyload" data-bgset="img-1.jpg (max-width: 480px), img-2.jpg (max-width: 1024px), img-3.jpg">
</div>
```

Is this working for you know? Can you please re-test in general as also in Chrome (Could not reproduce this with Chrome Canary or Chrome stable)

**Comment by aFarkas** [comment] 2015-01-30 17:30
In case you are interested in this, I can work something out. I think a lot of people might want something like this. (As long as object fit isn't supported by modern IE). Just let me know...

**Comment by TPDBrendan** [comment] 2015-01-30 17:49
I thought I must be missing something - I see what you mean now.  I would certainly use it if you were to work on it and I think you're right that this would be useful for a lot of people.  Yea, the mediaset example you gave above is the format I was expecting.  Here's the way that my current solution works using enquireJS:

// HTML
<div class="billboard-image" style="background-image:url('.../image.jpg');" data-smallbanner="../image.jpg" data-largebanner="../lrg_image.jpg"></div>

// JS

enquire.register("screen and (min-width:768px)", {

      // Triggered when a media query matches.
      match : function() {
        $('.billboard-image').each(function(){
            var lrg = $(this).data('largebanner');
            $(this).css('background-image','url(' + lrg + ')');  
          }); 
      },
      unmatch : function() {
        $('.billboard-image').each(function(){
          var sml = $(this).data('smallbanner');
          $(this).css('background-image','url(' + sml + ')');  
        }); 
      }

  });

**Comment by aFarkas** [comment] 2015-01-31 17:30
I have just extended the bgset plugin to also support art direction. 

Here is the documentation:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset
Here is the demo:
http://jsfiddle.net/trixta/bfqqnosp/embedded/result/

Note: You need to update also lazysizes itself not just the plugin to get this to work.

Please close, if this makes you happy ;-).

**Comment by aFarkas** [comment] 2015-02-11 19:27
Just did some test and I might have found and fixed the problem in your enviroment. The fix is included in the master branch. Note: that you need to update both [lazysizes core](https://rawgit.com/aFarkas/lazysizes/master/lazysizes.min.js) as also the [bgset plugin](https://rawgit.com/aFarkas/lazysizes/master/plugins/bgset/ls.bgset.min.js) for this.

Another nice feature, I just added is a [extreme lightweight respimg polyfill for lazySizes](https://github.com/aFarkas/lazysizes/tree/master/plugins/respimg). Instead of being a full polyfill, I constrained the feature set so that you can actually implement all use cases of responsive images, but with a limited markup syntax, as result it is extreme small and fast.

**Comment by aFarkas** [comment] 2015-02-17 10:47
@TPDBrendan 
Could you test the 1.0.0-RC1 version for me and report if your problem still occurs?

**Comment by TPDBrendan** [comment] 2015-02-18 16:05
Hey!  Sorry for the delay, yesterday was quite busy after the long weekend.  Unfortunately, it still seems to be lagging a bit on my local version.  It's odd, it seems to have the most difficulty when I'm decreasing viewport width, but not as much when increasing it.  The link below is a screencast of the issue in question, I hope that helps a bit.

https://db.tt/u0I4cdXU

**Comment by aFarkas** [comment] 2015-02-19 23:12
Sorry, this doesn't ring a bell. If it is possible you can mail me your testcase or an url, so that I can debug the problem.

**Comment by aFarkas** [comment] 2015-02-27 18:46
If you can mail me or if side is online drop a link would be great. Until then I'm closing this

**Closed by aFarkas** 2015-02-27 18:46 UTC
