### ISSUE TITLE
Bgset on iOS 8 doesn't set background-image sometimes

### ISSUE THREAD

**Issue by sjelfull** [aFarkas/lazysizes#155] opened 2015-09-15 12:44 UTC
I'm using this markup with latest lazysizes (the patched version you gave me in another thread) on iOS 8:

```html
<div class="intro__perfect-family lazyload" 
data-bgset="/assets/img/frontpage/04Assets/optimized/perfect-family@1x.png 1x, 
/assets/img/frontpage/04Assets/optimized/perfect-family@2x.png 2x"></div>
```

When inspecting the page, it has the following:
- A *lazyloaded* class
- A inline, hidden <picture> element:
```html
<picture style="display: none;"><source data-srcset="/assets/img/frontpage/04Assets/optimized/perfect-family@1x.png 1x, /assets/img/frontpage/04Assets/optimized/perfect-family@2x.png 2x" 
sizes="320px" srcset="/assets/img/frontpage/04Assets/optimized/perfect-family@1x.png 1x, 
/assets/img/frontpage/04Assets/optimized/perfect-family@2x.png 2x">
<img class="lazyautosizes lazyloaded" data-sizes="auto" sizes="320px"></picture>
```

It does not have a background set on it, though. Wierd. You can see the site here: dagligbrod.sidekick.work

**Comment by aFarkas** [comment] 2015-09-15 17:23
This is not a bug, but a [constrain of the respimg plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg#constrained-markup-support).  As stated there, you can only use srcset with width descriptors (w) not density descriptors (x). If you don't like this, you can use a full polyfill or simply switch to the width descriptor (i.e.: the width descriptor is more powerfull than the x descriptor and includes all feature, that the x descriptor has).

The following code should work:

```html
<div class="intro__perfect-family lazyload" 
data-bgset="/assets/img/frontpage/04Assets/optimized/perfect-family@1x.png 2577w, 
/assets/img/frontpage/04Assets/optimized/perfect-family@2x.png 5154w" data-sizes="auto"></div>
```

I would actually also add a 1200w image. 2500w is quite to heavy.

Please close this issue if it helped.

**Comment by sjelfull** [comment] 2015-09-17 20:58
Thanks, worked just fine!

**Closed** 2015-09-17 20:58 UTC
