### ISSUE TITLE
srcset on safari

### ISSUE THREAD

**Issue by lekoala** [aFarkas/lazysizes#39] opened 2015-01-13 16:36 UTC
Hi! 

I have a strange issue on safari (latest version)

There is a strange data-risrc and data-risrcset that is added and the image is not displaying. I've been looking at your code but I don't see any function that does this...

Sample html below:

	<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" 
	data-srcset="/assets/SetWidth320213-Screen-Shot-2015-01-13-at-15.40.30.png 320w,
	/assets/SetWidth640426-Screen-Shot-2015-01-13-at-15.40.30.png 640w,
	/assets/SetWidth960639-Screen-Shot-2015-01-13-at-15.40.30.png 960w,
	/assets/SetWidth1280852-Screen-Shot-2015-01-13-at-15.40.30.png 1280w" 
	data-sizes="auto" alt="Screen Shot 2015 01 13 at 15.40.30" 
	class=" lazyloaded lazyautosizes" sizes="293px" 
	srcset="" 
	data-risrc="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" 
	data-risrcset="/assets/SetWidth320213-Screen-Shot-2015-01-13-at-15.40.30.png 320w,/assets/SetWidth640426-Screen-Shot-2015-01-13-at-15.40.30.png 640w,
	/assets/SetWidth960639-Screen-Shot-2015-01-13-at-15.40.30.png 960w,
	/assets/SetWidth1280852-Screen-Shot-2015-01-13-at-15.40.30.png 1280w" width="293" style="">

**Comment by aFarkas** [comment] 2015-01-13 19:40
Hi,

I just tried to reproduce it, but couldn't. I tested in Safari 7.1.2 and Safari for iOS 8.1 (currently no Safari 8 for OSX).

I assume your initial markup looks something like this?

```html
<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
	 data-srcset="/assets/SetWidth320213-Screen-Shot-2015-01-13-at-15.40.30.png 320w,
/assets/SetWidth640426-Screen-Shot-2015-01-13-at-15.40.30.png 640w,
/assets/SetWidth960639-Screen-Shot-2015-01-13-at-15.40.30.png 960w,
/assets/SetWidth1280852-Screen-Shot-2015-01-13-at-15.40.30.png 1280w"
	 data-sizes="auto" alt="Screen Shot 2015 01 13 at 15.40.30"
	 class="lazyload"
	 style="">
```

The ``data-ri*`` attributes are coming from respimage polyfill, because it destroys the original ``src`` and ``srcset`` attributes to make it easy to still get the original values.

In case you have iOS 8.1 or a Safari 7.1.2 can you reproduce it there? Can you create a simplified testcase? Do you have any JS errors in your console? Can you reproduce this bug with this fiddle: http://jsfiddle.net/trixta/qoxrw9n1/?

**Comment by aFarkas** [comment] 2015-01-17 11:34
@lekoala 
Can you give more information. I really want to help out here!

**Comment by lekoala** [comment] 2015-01-19 15:38
Hi,

Thanks for your help. The jsfiddle works just fine each time, so it might be another issue here.

I was lazyloading the polyfill with the following code, and this is what seems to trigger the issue (also some strange stuff in firefox regarding loading background images)

	function __loadJS(u){var r = document.getElementsByTagName( "script" )[ 0 ], s = document.createElement( "script" );s.src = u;r.parentNode.insertBefore( s, r );}

	if(!window.HTMLPictureElement){
		__loadJS("$basePath/respimage.min.js");
	}

By loading it up front, no issues anymore. Now, I have another issue, there are some strange glitches before the image is completely loaded, maybe this is more related to the polyfill so I won't discuss it here.

**Comment by aFarkas** [comment] 2015-01-19 16:47
@lekoala 
I still can't reproduce this with conditionaly loading of the polyfill, but changed something that might help. I would appreciate if you could a) test the [new version in master](https://github.com/aFarkas/lazysizes/blob/master/lazysizes.min.js) with your old conditionally async include and b) also check with your new one.

**Comment by aFarkas** [comment] 2015-01-27 22:59
Any news on this bug? Have you tested the updated version???

**Comment by aFarkas** [comment] 2015-01-30 12:21
@lekoala 
I'm closing this. If you have still problems with the updated version, I would appreciate, if you would reopen this issue with some more information. Thank you.

**Closed by aFarkas** 2015-01-30 12:21 UTC

**Comment by joelparr** [comment] 2015-06-03 19:56
I'm getting this too in Safari on iOS 8.3.

Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4
